steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m rsync -r -d build gs://react-demo-app-bucket
        gsutil -h "Cache-Control:no-store" cp build/index.html gs://react-demo-app-bucket/index.html
        gsutil web set -m index.html -e 404.html gs://react-demo-app-bucket
        gsutil iam ch allUsers:objectViewer gs://react-demo-app-bucket

options:
  logging: CLOUD_LOGGING_ONLY
